[package]
name = "advent2019"
version = "0.1.0"
authors = ["anniecherk <anniecherk@galois.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dev-dependencies]
pretty_assertions = "0.6.0"
